name: Validate and build CLI

on:
  pull_request:
    paths:
      - 'cli/**'
  push:
    branches: [main]
    paths:
      - 'cli/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  ci-cli-python:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: cli
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Sync dependencies
        run: uv sync --all-extras

      - name: Run tests
        run: uv run pytest

      - name: Build dist
        run: uv build
